import { AbstractReportModel } from '../../models/AbstractReportModel';
import { NullReportModel } from '../../models/NullReportModel';
import { ReportModel } from '../../models/ReportModel';
import { Autonumberer } from '../Autonumberer';

export class ReportBuilder {
    constructor() {}

    /**
     * Builds a ReportModel from a dictionary of results generated by the analyzer strategy.
     * @param content The dictionary of results.
     * @returns The built AbstractReportModel.
     */
    public build(content: {}): AbstractReportModel {
        if (
            content === null ||
            content === undefined ||
            Object.keys(content).length === 0
        ) {
            return new NullReportModel();
        }

        return new ReportModel(
            Autonumberer.getInstance().generateNext() as string,
            content,
        );
    }

    /**
     * Builds a ReportModel from elements extracted from an XML file.
     * @param id The ID of the report.
     * @param results The XML elements containing the report data.
     * @returns The built AbstractReportModel.
     */
    public buildFrom(id: string, results: Element): AbstractReportModel {
        const loadedResults: { [key: string]: { [key: string]: number } } =
            this.buildResultDictionary(results);
        return new ReportModel(id, loadedResults);
    }

    /**
     * Formats the results from the XML file into a dictionary for use in the ReportModel.
     * @param results The XML elements containing the report data.
     * @returns The formatted dictionary of results.
     */
    public buildResultDictionary(results: Element): {
        [key: string]: { [key: string]: number };
    } {
        const extractValue = (
            tag: string,
            defaultValue: number = -1,
        ): number => {
            const element = results?.getElementsByTagName(tag)[0];
            return element ? Number(element.textContent) : defaultValue;
        };

        return {
            pubicSymphysis: {
                L: extractValue('L'),
                L_min: extractValue('L_min'),
                L_max: extractValue('L_max'),
                R: extractValue('R'),
                R_min: extractValue('R_min'),
                R_max: extractValue('R_max'),
                C: extractValue('C'),
                C_min: extractValue('C_min'),
                C_max: extractValue('C_max'),
            },
            sternalEnd: {
                L: extractValue('L'),
                L_min: extractValue('L_min'),
                L_max: extractValue('L_max'),
                R: extractValue('R'),
                R_min: extractValue('R_min'),
                R_max: extractValue('R_max'),
                C: extractValue('C'),
                C_min: extractValue('C_min'),
                C_max: extractValue('C_max'),
            },
            auricularSurface: {
                L: extractValue('L'),
                L_min: extractValue('L_min'),
                L_max: extractValue('L_max'),
                R: extractValue('R'),
                R_min: extractValue('R_min'),
                R_max: extractValue('R_max'),
                C: extractValue('C'),
                C_min: extractValue('C_min'),
                C_max: extractValue('C_max'),
            },
            thirdMolar: {
                TL: extractValue('TL'),
                TR: extractValue('TR'),
                BL: extractValue('BL'),
                BR: extractValue('BR'),
            },
        };
    }
}
